# Generated by Django 3.0.7 on 2020-06-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('nutrition_grade_fr', models.CharField(max_length=254)),
                ('quantity', models.CharField(max_length=254)),
                (
                    'ingredients_text',
                    models.TextField(default='no descripton'),
                ),
                (
                    'ingredients_text_with_allergens_fr',
                    models.TextField(default='no descripton'),
                ),
                ('url', models.URLField()),
                ('url_images', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'brands',
                    models.ManyToManyField(
                        blank=True, related_name='products', to='catlog.Brand'
                    ),
                ),
                (
                    'categories',
                    models.ManyToManyField(
                        blank=True,
                        related_name='products',
                        to='catlog.Category',
                    ),
                ),
                (
                    'stores',
                    models.ManyToManyField(
                        blank=True, related_name='products', to='catlog.Store'
                    ),
                ),
            ],
        ),
    ]
