# Generated by Django 3.0.7 on 2020-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand', name='active', field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='category', name='active', field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='store', name='active', field=models.BooleanField(),
        ),
    ]
