# Generated by Django 3.0.7 on 2020-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0003_auto_20200630_1035'),
    ]

    operations = [
        migrations.RemoveField(model_name='brand', name='created_at',),
        migrations.RemoveField(model_name='category', name='created_at',),
        migrations.RemoveField(model_name='product', name='created_at',),
        migrations.RemoveField(model_name='store', name='created_at',),
    ]
