# Generated by Django 3.0.7 on 2020-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_auto_20200630_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='brand', name='name', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='category', name='name', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='product', name='name', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='store', name='name', field=models.TextField(),
        ),
    ]
