# Generated by Django 3.0.7 on 2020-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0006_auto_20200630_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand', name='url', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category', name='url', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product', name='url', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product', name='url_images', field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store', name='url', field=models.TextField(),
        ),
    ]
